spring.application.name=ProyectoSpring01
logging.level.root=INFO
logging.level.com.pepe.ProyectoSpring01=WARN
logging.file.name=mis_springs.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB